name: upload auto-deployment and function zip files into AWS S3 bucket
on:
  workflow_dispatch:
  workflow_run:
    workflows: ["unit tests and code-coverage"]
    types:
      - completed
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: '1.x'
      - name: Build and zip binary file
        run: |
          GOOS=linux go build -o bootstrap main.go
          zip function.zip ./bootstrap
          cp function.zip ./aws
      - name: Upload files into S3 bucket
        run: |
          cd action
          go run run.go
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: us-east-1
          BUCKET_NAME: logzio-aws-integrations-us-east-1
          BUCKET_DIR: api-status-auto-deployment
          SRC_DIR: ../aws
          AUTO_DEPLOYMENT_FILE: auto-deployment.yaml
          FUNCTION_ZIP_FILE: function.zip